# Site settings
title: Прогулка по рельсу
email: z@illus0r.net
baseurl: '' # the subpath of your site, e.g. /blog/
url: http://dianov.org # the base hostname & protocol for your site
twitter_username: z_o_r
github_username:  illus0r

# Build settings
markdown: kramdown